# Generated by Django 4.1.4 on 2022-12-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fuel_UR_Way', '0002_cartype_fueltype_payments_rename_owner_car_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.AddField(
            model_name='order',
            name='carType',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fuelType',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='litter',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='payed',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
