# Generated by Django 4.1.4 on 2022-12-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fuel_UR_Way', '0003_remove_order_car_order_cartype_order_fueltype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extraService',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
